# serverless.ym

service: hello-world

provider:
  name: aws
  runtime: nodejs12.c
  stage: dev

functions:
  hello:
    handler: ./handler.hello
    events:
      - http:
          path: hello
          method: GET
          cors: true
